version: 2

project_name: pulse

builds:
  - id: pulse
    env:
      - CGO_ENABLED=0
    main: .
    binary: pulse
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

dockers:
  - image_templates:
      - "ghcr.io/ajansari95/pulse:{{ .Tag }}"
      - "ghcr.io/ajansari95/pulse:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"

changelog:
  sort: asc
